# https://github.com/mitchellh/vagrant-aws
# vagrant plugin install vagrant-aws
# vagrant up --provider=aws



###
#
# This script will install composer development environment on AWS
# in order to run this you will need vagrant-aws plugin installed
# vagrant plugin install vagrant-aws
#
#
# This script expect the following
# - work on region eu-west-1
# - environment variables: COMPOSER_KEY, COMPOSER_ACCESS_KEY
# - keypair located at ./dev/composer.pem (where . is the Vagrantfile folder) with chmod 600
# - ./synced_folder/dev/cloudify-blueprint-composer-master.zip
# - ./synced_folder/dev/cloudify-blueprint-topology.master.zip
# - keypair with name composer matching the composer.pem file on given account
#
#
# run this vagrant file with vagrant up --provider=aws
#
###

Vagrant.configure("2") do |config|

  config.vm.box = "composer-setup-dev-enviroment"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

  # please note - in aws provider the flag is NOT rsync__exclude but instead rsync_exclude (single underscore, not double)
  # https://github.com/mitchellh/vagrant-aws/pull/156
  config.vm.synced_folder "./synced_folder", "/vagrant", type: "rsync"

  config.vm.provision "shell" do |s|
    s.path = "./provision.sh"
    s.privileged = false
  end

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ENV['COMPOSER_KEY']
    aws.secret_access_key = ENV['COMPOSER_ACCESS_KEY']
    aws.keypair_name = 'composer'

    aws.region = 'eu-west-1'
    aws.instance_type = 'm3.large'
    aws.ami = 'ami-47a23a30' # ubuntu

    aws.tags = {
        'Name' => 'composer-dev-env'
    }

    override.ssh.username = 'centos'
    override.ssh.private_key_path = './dev/composer.pem'
    # http://stackoverflow.com/questions/33098913/vagrant-fails-to-get-machine-up-throwing-keep-getting-an-error-prompt-undef?noredirect=1#comment54025480_33098913
    override.ssh.insert_key = false


  end
end